/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package deploy;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertTrue(classUnderTest.someAppMethod(), "app.someAppMethod() should return true");
    }
}
